# Graphics
FPS = 60
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Colours
BLACK = 'black'
WHITE = 'white'
GREY = 'grey'

# Board
NO_TILES = 10
BLOCK_WIDTH = SCREEN_WIDTH / NO_TILES
BLOCK_HEIGHT = SCREEN_HEIGHT / NO_TILES